services:
#  fpt.teammatching.api:
#    image: fpt.teammatching.api
#    build:
#      context: .
#      dockerfile: FPT.TeamMatching.API/Dockerfile
  redis:
    image: redis:7.0
    container_name: fpt.matching.redis
    ports:
      - "6379:6379"
