networks:
  default:
    external: true
    name: my-network
services:
  fpt.teammatching.api:
    image: fpt.teammatching.api
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: FPT.TeamMatching.API/Dockerfile
    env_file:
      - FPT.TeamMatching.API/.env
  redis:
    image: redis:7.0
    container_name: fpt.matching.redis
    ports:
      - "6379:6379"
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: fpt.matching.zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: quay.io/debezium/kafka:2.7
    container_name: fpt.matching.kafka
    restart: always
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - ZOOKEEPER_CONNECT=fpt.matching.zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://fpt.matching.kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ACKS=manual
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fpt.matching.kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: fpt.matching.kafka:9092
    ports:
      - "9089:8080"
    links:
      - kafka