name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cài đặt Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build the Docker image
      run: docker build -f FPT.TeamMatching/Dockerfile FPT.TeamMatching/ --tag sonnh37/fpt-team-matching-backend:latest

    # Push Docker image lên Docker Hub
    - name: Push Docker image
      run: docker push sonnh37/fpt-team-matching-backend:latest
